In [1]:
pip install alpha_vantage

Requirement already satisfied: alpha_vantage in d:\dell\workshop\lib\site-packages (2.3.1)
Requirement already satisfied: requests in d:\dell\workshop\lib\site-packages (from alpha_vantage) (2.22.0)
Requirement already satisfied: aiohttp in d:\dell\workshop\lib\site-packages (from alpha_vantage) (3.7.4.post0)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\dell\appdata\roaming\python\python37\site-packages (from aiohttp->alpha_vantage) (3.7.4.3)
Requirement already satisfied: async-timeout<4.0,>=3.0 in d:\dell\workshop\lib\site-packages (from aiohttp->alpha_vantage) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in d:\dell\workshop\lib\site-packages (from aiohttp->alpha_vantage) (19.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\dell\workshop\lib\site-packages (from aiohttp->alpha_vantage) (5.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\dell\workshop\lib\site-packages (from aiohttp->alpha_vantage) (1.6.3)
Requirement already satisfied: chardet<5.0,>=2.0 in d:\dell\workshop\lib\site-packages (from aiohttp->alpha_vantage) (3.0.4)
Requirement already satisfied: idna>=2.0 in d:\dell\workshop\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->alpha_vantage) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\dell\workshop\lib\site-packages (from requests->alpha_vantage) (1.24.2)
Requirement already satisfied: certifi>=2017.4.17 in d:\dell\workshop\lib\site-packages (from requests->alpha_vantage) (2019.9.11)
Note: you may need to restart the kernel to use updated packages.

In [15]:
from alpha_vantage.timeseries import TimeSeries

key = 'AAX6QCWZGFTK11MX'
outputsize = 'compact'
symbol = input('Ticker : ')
typ = input('Data type- "daily", "weekly", "monthly", "interval" : ')
state = ts.get_daily_adjusted(symbol,outputsize=outputsize)[0]
ts = TimeSeries(key,output_format='pandas')

if typ == 'daily':
    state = ts.get_daily_adjusted(symbol,outputsize=outputsize)[0]
elif typ == 'weekly':
    state = ts.get_weekly_adjusted(symbol)[0]
elif typ == 'monthly':
    state = ts.get_monthly_adjusted(symbol)[0]
elif typ == 'interval':
    interval = input('Interval-1min, 5min, 15min, 30min, 60min : ')
    state = ts.get_intraday(symbol, interval=interval, outputsize=outputsize)[0]
else:
    print('Wrong entry')
state

Ticker : SPY
Data type- "daily", "weekly", "monthly", "interval" : daily

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient
date,,,,,,,,
2021-04-21,411.51,416.2900,411.36,416.07,416.070000,66792983.0,0.0,1.0
2021-04-20,413.91,415.0859,410.59,412.17,412.170000,81851828.0,0.0,1.0
2021-04-19,416.26,416.7400,413.79,415.21,415.210000,78498496.0,0.0,1.0
2021-04-16,417.25,417.9100,415.73,417.26,417.260000,82037278.0,0.0,1.0
2021-04-15,413.74,416.1600,413.69,415.87,415.870000,60229842.0,0.0,1.0
...,...,...,...,...,...,...,...,...
2020-12-02,364.82,366.9600,364.20,366.79,364.032617,45927000.0,0.0,1.0
2020-12-01,365.57,367.6800,364.93,366.02,363.268405,72509670.0,0.0,1.0
2020-11-30,362.83,363.1200,359.17,362.06,359.338175,83872709.0,0.0,1.0
2020-11-27,363.84,364.1800,362.58,363.67,360.936072,28514072.0,0.0,1.0
2020-11-25,363.13,363.1600,361.48,362.66,359.933665,45330890.0,0.0,1.0

In [12]:
from alpha_vantage.techindicators import TechIndicators

key = 'AAX6QCWZGFTK11MX'
symbol = input('Ticker : ')
outputsize = 'compact'
interval =input('Interval- 1min,5min,15min,30min,60min,daily,weekly,monthly : ')
time = input('Time Period : ')
tech_indi = input('Technical Indicator- SMA,EMA,VWAP,MACD,Stochastic Oscillator,RSI,Bollinger bands :')

ti = TechIndicators(key,output_format='pandas')

if tech_indi == 'SMA':
    state = ti.get_sma(symbol, interval=interval, time_period=time, series_type='close')[0]
elif tech_indi == 'EMA':
    state = ti.get_ema(symbol, interval=interval, time_period=time, series_type='close')[0]
elif tech_indi == 'VWAP':
    state = ti.get_vwap(symbol, interval=interval)[0]
elif tech_indi == 'MACD':
    state = ti.get_macd(symbol, interval=interval, series_type='close')[0]
elif tech_indi == 'Stochastic Oscillator':
    state = ti.get_stoch(symbol, interval=interval)[0]
elif tech_indi == 'RSI':
    state = ti.get_rsi(symbol, interval=interval, time_period=time, series_type='close')[0]
elif tech_indi == 'Bollinger bands':
    state = ti.get_bbands(symbol, interval=interval, time_period=time, series_type='close')[0]
else:
    print('Wrong Entry')
state

Ticker : SPY
Interval- 1min,5min,15min,30min,60min,daily,weekly,monthly : daily
Time Period : 30
Technical Indicator- SMA,EMA,VWAP,MACD,Stochastic Oscillator,RSI,Bollinger bands :SMA

                 SMA
date
1999-12-13   93.9351
1999-12-14   94.0510
1999-12-15   94.2054
1999-12-16   94.3535
1999-12-17   94.4989
...              ...
2021-04-15  396.5517
2021-04-16  397.9447
2021-04-19  399.0392
2021-04-20  400.0958
2021-04-21  401.1014

[5373 rows x 1 columns]